### ISSUE TITLE
[question] Confusion over null comparisons

### ISSUE THREAD

**Issue by jasal82** [koto-lang/koto#268]
I have a user-defined struct type `X` mapped into Koto. A free constructor method returns either `Ok(X)` or `Ok(Value::Null)` to indicate an empty result. Now if I assign that result to a variable in Koto `x = generate_x()` I can do this for example:

```
if x
  print "valid"
```

But I cannot do this:

```
assert_ne(x, null)
```

This will give me an error about `@!=` not being implemented for `X`. So my questions are as follows:

- Is it bad design to return `null` to indicate an empty result?
- What would be better? Return an `Err` or give `X` a method to check for an empty result? (I guess that's pretty much the same question that lead to `Option<T>` in Rust)
- Why does `if x` work but not the assertion?

**Comment by irh** [comment]
I think returning `null` from a constructor is fine, it communicates the equivalent of returning an `Option<T>` in Rust, which seems reasonable enough to me.

You've exposed a bit of a gotcha with the current `Object` system though...

- `if x` works because of the [truthiness rules](https://koto.dev/docs/next/language/#truthiness); anything that isn't `false` or `null` is evaluated as `true` in a boolean context.
- `assert_ne(null, x)` works because the operator system prioritises the value on the LHS: the assertion will pass for any RHS value except for `null`.
- `assert_ne(x, null)` doesn't work because when an `Object` is on the LHS it unconditionally defers to the object's `KotoObject::not_equal` implementation.

I suspect that `null` on the RHS of equality comparisons is worth treating as a special case, I can't think of a good reason to want to customize the behaviour, and it seems like forcing implementations of `equal/not_equal` to avoid this kind of surprise would irritating for implementors..

**Comment by jasal82** [comment]
Thanks, that makes sense. It looks as if special treatment is indeed necessary here.
