### ISSUE TITLE
take() with predicate broken?

### ISSUE THREAD

**Issue by jasal82** [koto-lang/koto#349]
I'm trying to use the iterator `take()` method with a predicate, but if I do the following simple test
```
x = [1, 2, 3, 4]
y = x.take(|i| i > 1).to_list()
```
I get an empty list in `y`.

**Comment by irh** [comment]
Hi @jasal82 - `take` with a predicate is used to consume values from the iterator as long as the predicate returns `true`, and it stops providing values as soon as the predicate returns `false`. In your example the first value fails the test, and so the result is an empty list.

`keep` might be what you're looking for instead?

**Comment by jasal82** [comment]
Ah I see, the documentation currently allows for multiple interpretations ;) Thanks for the clarification.

**Comment by irh** [comment]
@jasal82 Did you look at the latest docs? They've been updated since v0.14 with the goal of making `take`'s behaviour a bit clearer, see https://koto.dev/docs/next/core/iterator/#take

If the latest version is still confusing please let me know, and I'd be happy to hear suggestions for how it could be improved.
