### ISSUE TITLE
Bitwise operations are missing

### ISSUE THREAD

**Issue by ales-tsurko** [koto-lang/koto#37]
Raised in #36 

That would also be great not only have bitwise operations on numbers, but also being able to overload bitwise operators (when #36 be ready).

**Comment by irh** [comment]
I thought about this a little this morning, and I think it would be great to add bitwise operations for integer numbers, but I think operators might be tricky.

`|` is used as the 'function start' character, and my hunch is that getting the parser to distinguish between 'function start' and 'bitwise or' is going to add significant complexity, if it's even possible given the current grammar. e.g. `a | b | c` - should that be parsed as two bitwise operations, or a call to `a` with a function that has `b` as its argument and `c` as its body?

The cleanest approach that I can think of then is to have bitwise functions available in the `number` module (`and`, `or`, etc), allowing for `a.or c.or d`. `foo.and bar.xor baz`..

Other alternatives:
- Have typical bitwise operators, except for `or`, which just uses the `or` keyword (this would take some re-jigging in the compiler but it should be doable).
- Insist on parentheses for function calls.
  - This seems like a pretty big price to pay just for having an `|` operator
- Find another character for defining functions
- Introduce `->` (or something) to mark the start of the function body.

Maybe there are more options, but so far each has an impact that I'd rather avoid.

**Comment by ales-tsurko** [comment]
> * Have typical bitwise operators, except for `or`, which just uses the `or` keyword (this would take some re-jigging in the compiler but it should be doable).

I vote for this. But the `or` keyword for bitwise operation might be confusing as it's usually a logical operator.

**Comment by ales-tsurko** [comment]
Another option could be functions without anything around arguments, something like:

```
sum = fn a, b, a + b
```

This way it looks like a function call and I think it's interesting, because syntactically even to define a function you use another function to do it. Arguments could be determined by comma, so the last thing in this construction would be the function body. If there are no commas/ there's only one "argument", it's a function without arguments:

```
z = fn "hello".print
```

Not sure about nested functions though. Even if the same parser would still work, it might be hard to read. But it can be improved.

**Comment by irh** [comment]
I just merged #50 which will be good ground work for adding bitwise operations.

**Comment by irh** [comment]
> But the or keyword for bitwise operation might be confusing as it's usually a logical operator.

Yes, this inconsistency seems like a dealbreaker to me.

> Another option could be functions without anything around arguments...

Thanks for the suggestion @ales-tsurko, I'm not _totally_ against changing the function syntax, and it's worth considering (although at this point I'm quite attached to the `||` style for various reasons), but I think it's a much larger problem that probably deserves a separate discussion thread.

So for now, I'll follow the path of least resistance and add bit-tweaking operations to `number` so that it's at least possible in the language, and then close this issue. I'll see if I have time today to write up my thoughts for a discussion on why I've chosen `||` and what the design goals would be in considering alternatives. And I'd be OK with engaging in a discussion on whether or not bitwise operators belong in the language (assuming there's a solution for `|`), I can see pros and cons for both sides there.
